<?php
// index.php - Single page portfolio (PHP file so contact form can post to PHP backend)
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Sriraj — Personal Portfolio</title>
  <link rel="stylesheet" href="css/style.css">
</head>
<body>
  <header class="site-header">
    <div class="container">
      <h1 class="name">Sriraj</h1>
      <nav class="nav">
        <a href="#home">Home</a>
        <a href="#about">About</a>
        <a href="#skills">Skills</a>
        <a href="#projects">Projects</a>
        <a href="#contact">Contact</a>
      </nav>
    </div>
  </header>

  <main>
    <section id="home" class="hero">
      <div class="container">
        <h2>Hi — I'm <span>Sriraj</span></h2>
        <p>Web developer · JavaScript · PHP · Designer</p>
        <a class="cta" href="#projects">See my work</a>
      </div>
    </section>

    <section id="about" class="panel">
      <div class="container">
        <h3>About Me</h3>
        <p>I'm a full-stack developer who builds modern, responsive websites using HTML, CSS, JavaScript and PHP. I enjoy turning ideas into digital products.</p>
      </div>
    </section>

    <section id="skills" class="panel">
      <div class="container">
        <h3>Skills</h3>
        <ul class="skills-list">
          <li>HTML &amp; CSS (Responsive)</li>
          <li>JavaScript (ES6+)</li>
          <li>PHP &amp; Backend basics</li>
          <li>MySQL (basic)</li>
          <li>Version control (Git)</li>
        </ul>
      </div>
    </section>

    <section id="projects" class="panel">
      <div class="container">
        <h3>Projects</h3>
        <div class="projects-grid" id="projectsGrid">
          <!-- Project cards generated by JS -->
        </div>
      </div>
    </section>

    <section id="contact" class="panel">
      <div class="container">
        <h3>Contact</h3>
        <form id="contactForm" method="post" action="contact.php">
          <label>
            Name
            <input type="text" name="name" id="name" required>
          </label>
          <label>
            Email
            <input type="email" name="email" id="email" required>
          </label>
          <label>
            Message
            <textarea name="message" id="message" rows="5" required></textarea>
          </label>
          <button type="submit">Send Message</button>
          <p id="formStatus" role="status" aria-live="polite"></p>
        </form>
      </div>
    </section>
  </main>

  <footer class="site-footer">
    <div class="container">
      <p>© <?php echo date('Y'); ?> Sriraj — Built with HTML/CSS/JS/PHP</p>
    </div>
  </footer>

  <script src="js/main.js"></script>
</body>
</html>
